# Generated by Django 4.2.13 on 2024-06-02 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_service_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentgame',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tornament', to='tournament_service_app.tournament'),
        ),
        migrations.AlterField(
            model_name='tournamentparticipant',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournament_service_app.tournament'),
        ),
    ]
