# Generated by Django 4.2.13 on 2024-06-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_service_app', '0003_tournament_round_now_tournamentgame_game_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentparticipant',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
