# Generated by Django 4.2.2 on 2024-06-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service_app', '0002_gameappearance_theme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerstats',
            old_name='total_score',
            new_name='tournament_played',
        ),
        migrations.AddField(
            model_name='playerstats',
            name='tournament_point_porcent',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='tournament_won',
            field=models.IntegerField(default=0),
        ),
    ]
