# Generated by Django 4.2.2 on 2024-05-31 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_service_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerStats',
        ),
    ]
