# Generated by Django 4.2.2 on 2024-06-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_service_app', '0003_alter_game_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
