{
 "title": "Pong Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Prometheus", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(django_http_responses_total_by_status_total, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage by Job",
   "type": "gauge",
   "description": "This graph displays the CPU usage for the selected job over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  sum by (instance) (\n    rate(process_cpu_seconds_total{job=~\"$job\"}[$__rate_interval])\n  ),\n  \"instance\", \"$1\", \"instance\", \"(.*):.*\"\n)\n",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory Usage for Selected Job",
   "type": "gauge",
   "description": "This graph displays the memory usage for the selected job over time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  sum by (instance) (\n    process_resident_memory_bytes{job=~\"$job\"}\n  ),\n  \"instance\", \"$1\", \"instance\", \"(.*):.*\"\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "HTTP Request Volume by Service",
   "type": "timeseries",
   "description": "This graph displays the rate of HTTP requests received by each service over time. The data is aggregated by job and shows the number of requests per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (job) (\n  rate(django_http_requests_total_by_method_total{job=~\"$job\"}[$__rate_interval])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Latency (P95) by Service",
   "type": "timeseries",
   "description": "This graph displays the 95th percentile latency of HTTP requests for each service over time. The data shows the latency experienced by the slowest 5% of requests",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_including_middlewares_seconds_bucket{job=~\"$job\"}[$__rate_interval])) by (le, job))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Success Rate by Service",
   "type": "timeseries",
   "description": "This graph displays the success rate of HTTP requests for each service over time. The data shows the proportion of successful requests (status 2xx and 3xx) out of the total requests.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "(\n  sum by (job) (\n    rate(django_http_responses_total_by_status_total{status=~\"2..|3..\", job=~\"$job\"}[$__rate_interval])\n  )\n  /\n  sum by (job) (\n    rate(django_http_requests_total_by_method_total{job=~\"$job\"}[$__rate_interval])\n  )\n) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Error Rates by Service",
   "type": "timeseries",
   "description": "This graph displays the rate of HTTP errors (status 4xx and 5xx) for each service over time. The data shows the number of error responses per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (job, status) (\n  rate(django_http_responses_total_by_status_total{status=~\"4..|5..\", job=~\"$job\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}